### ISSUE TITLE
GILA KEREN BANGET SIH

### ISSUE THREAD

**Issue by yasirabd** [Ajisaputrars/Dicoding-KADE-Final-Project#1]
### ANDALANQU

NDANG LULUS NDES!!
KEREN BANGET POKOE!!
@Ajisaputrars

**Comment by Ajisaputrars** [comment]
tekke malah open issue, starnya jangan lupa

**Comment by Ajisaputrars** [comment]
starnya jangan lupa

**Comment by yasirabd** [comment]
> tekke malah open issue, starnya jangan lupa

**Comment by dzulfikar68** [comment]
Ngeriiii mainane swifttt
